### ISSUE TITLE
removing a experiments from the database corrupts the view due to inconsistent row ID

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#158]
if an experiment is removed from the DB (or the entire DB) and the server is re-run, no plots can be added. 
This occurs if a row was previously selected that no longer exists. 
This problem is resolved if browser cookies are cleared. 
example error message: 
```
IndexError: list index out of range
ERROR:entropylab.results.dashboard.dashboard:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "c:\users\gal\scoop\apps\python37\current\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    rv = self.handle_user_exception(e)
    rv = self.dispatch_request()
  File "c:\users\gal\scoop\apps\python37\current\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\gal\scoop\apps\python37\current\lib\site-packages\dash\dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "c:\users\gal\scoop\apps\python37\current\lib\site-packages\dash\_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "c:\users\gal\scoop\apps\python37\current\lib\site-packages\entropylab\results\dashboard\dashboard.py", line 95, in render_plot_tabs_from_selected_experiments_table_rows
    exp_id = data[row_num]["id"]
IndexError: list index out of range

```

**Comment by urig** [comment]
Hi @galwiner . I wasn't able to reproduce this. Can we schedule time to go over it together?

**Comment by urig** [comment]
@galwiner, I was able to reproduce and fix. Can I ask you to verify PR https://github.com/entropy-lab/entropy/pull/180? Tx 🙏
